name: Terraform Trivy Scan

on:
  push:
    paths:
    - '**.tf'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)/trivy_$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)_Linux-64bit.deb
        sudo dpkg -i trivy_$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep tag_name | cut -d '"' -f 4)_Linux-64bit.deb

    - name: Run Trivy scan for Terraform
      run: |
        trivy fs --severity HIGH,CRITICAL --input /path/to/your/terraform/files
