name: Terraform Trivy Scan

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - feature/*
      - hotfix/*

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-ref: ./envs/dev/main.tf
        trivy-config: ./envs/dev/trivy.yaml
        trivyignores: ./envs/dev/trivyignore.yaml
        list-all-pkgs: true
