name: echo_hello

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'input message'
        required: true
        default: 'dev'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  echo_hello:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: echo message
        run: echo ${{ github.event.inputs.message }}
