name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'select dev or stg or prd'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: Terraform Apply - ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: AWS OIDC credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.OIDC_ROLE }}
          aws-region: ap-northeast-1

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./envs/${{ github.event.inputs.env }}

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: terraform refresh
        run: terraform refresh -no-color -lock=false -var="env=${{ github.event.inputs.env }}"
        working-directory: ./envs/${{ github.event.inputs.env }}

      - name: Terraform Plan
        run: |
          terraform plan \
            -no-color \
            -lock=false \
            -var="env=${{ github.event.inputs.env }}"
        working-directory: ./envs/${{ github.event.inputs.env }}

      - name: Terraform Apply
        run: |
          terraform apply \
            -no-color \
            -auto-approve \
            -lock=false \
            -var="env=${{ github.event.inputs.env }}"
        working-directory: ./envs/${{ github.event.inputs.env }}
